PIPER_BIN = "C:\\Users\\Pidge\\Downloads\\ProxiTalk\\piper\\piper.exe"
MODEL_PATH = "C:\\Users\\Pidge\\Downloads\\ProxiTalk\\piper\\en_GB-cori-medium.onnx"
CACHE_DIR = "C:\\Users\\Pidge\\Downloads\\ProxiTalk\\piper_cache"
APPS_DIR = "C:\\Users\\Pidge\\Downloads\\ProxiTalk\\apps"
ICON_DIR = "C:\\Users\\Pidge\\Downloads\\ProxiTalk\\icons"
FONT_PATH = "C:\\Users\\Pidge\\Downloads\\ProxiTalk\\DejaVuSans.ttf"
AUTOCOMPLETE_PATH = "C:\\Users\\Pidge\\Downloads\\ProxiTalk\\config\\autocomplete_words.txt"