WIN_TO_LINUX_KEYCODE = {
    'a': 'KEY_A',
    'b': 'KEY_B',
    'c': 'KEY_C',
    'd': 'KEY_D',
    'e': 'KEY_E',
    'f': 'KEY_F',
    'g': 'KEY_G',
    'h': 'KEY_H',
    'i': 'KEY_I',
    'j': 'KEY_J',
    'k': 'KEY_K',
    'l': 'KEY_L',
    'm': 'KEY_M',
    'n': 'KEY_N',
    'o': 'KEY_O',
    'p': 'KEY_P',
    'q': 'KEY_Q',
    'r': 'KEY_R',
    's': 'KEY_S',
    't': 'KEY_T',
    'u': 'KEY_U',
    'v': 'KEY_V',
    'w': 'KEY_W',
    'x': 'KEY_X',
    'y': 'KEY_Y',
    'z': 'KEY_Z',

    '1': 'KEY_1',
    '2': 'KEY_2',
    '3': 'KEY_3',
    '4': 'KEY_4',
    '5': 'KEY_5',
    '6': 'KEY_6',
    '7': 'KEY_7',
    '8': 'KEY_8',
    '9': 'KEY_9',
    '0': 'KEY_0',

    'space': 'KEY_SPACE',
    'tab': 'KEY_TAB',
    'enter': 'KEY_ENTER',
    'backspace': 'KEY_BACKSPACE',
    'minus': 'KEY_MINUS',
    'equal': 'KEY_EQUAL',
    'left bracket': 'KEY_LEFTBRACE',
    'right bracket': 'KEY_RIGHTBRACE',
    'semicolon': 'KEY_SEMICOLON',
    'apostrophe': 'KEY_APOSTROPHE',
    'comma': 'KEY_COMMA',
    'dot': 'KEY_DOT',
    'slash': 'KEY_SLASH',
    '/': 'KEY_SLASH',
    '?': 'KEY_SLASH',
    'grave': 'KEY_GRAVE',  # The backtick key `
    'backslash': 'KEY_BACKSLASH',
    '\\': 'KEY_BACKSLASH',
    '|': 'KEY_BACKSLASH',

    'volume up': 'KEY_VOLUMEUP',
    'volume down': 'KEY_VOLUMEDOWN',
    
    'esc': 'KEY_ESC',
    'escape': 'KEY_ESC',

    # Modifiers
    'left shift': 'KEY_LEFTSHIFT',
    'right shift': 'KEY_LEFTSHIFT',
    'shift': 'KEY_LEFTSHIFT', 
    
    'left ctrl': 'KEY_LEFTCTRL',
    'right ctrl': 'KEY_RIGHTCTRL',
    'ctrl': 'KEY_LEFTCTRL',
    
    'left alt': 'KEY_LEFTALT',
    'right alt': 'KEY_RIGHTALT',
    'alt': 'KEY_LEFTALT',
    
    # arrow keys
    'up': 'KEY_UP',
    'down': 'KEY_DOWN',
    'left': 'KEY_LEFT',
    'right': 'KEY_RIGHT',
}